
export default [
    {
        id: 1,
        img: "./img/Mục trang điểm/Ke-mat-Merzy-Perfect-Fixing-Pen-Eyeliner.jpg",
        text: "Kẻ Mắt Nước Merzy Perfect Fixing Pen Eyeliner 0.5gr",
        pr_sales: "110,000₫",
        price: "132,000₫",
    },
    {
        id: 2,
        img: "./img/Mục trang điểm/Merzy-The-Watery-Dew-Tint.jpg",
        text: "Son Tint Merzy The Watery Dew Tint 4gr",
        pr_sales: "170,000₫",
        price: "196,000₫",
    },
    {
        id: 3,
        img: "./img/Mục trang điểm/SON-KEM-FOIF-Daily-Velvet-Tint.jpg",
        text: "Son Kem FOIF Daily Velvet Tint 3gr",
        pr_sales: "140,000₫",
        price: "158,000₫",
    },
    {
        id: 4,
        img: "./img/Mục trang điểm/Phấn-Má-Hồng-Etude-House-Lovely-Cookie-Blusher-7gr.jpg",
        text: "Phấn Má Hồng Etude House Lovely Cookie Blusher 7gr",
        pr_sales: "110,000₫",
        price: "131,000₫",
    },
    {
        id: 5,
        img: "./img/Mục trang điểm/phan-mat-habaria-Professional-10.jpg",
        text: "Phấn Mắt Habaria Professional 10 Colors Professional Eyeshadow Palette 10gr",
        pr_sales: "95,000₫",
        price: "118,000₫",
    },
    {
        id: 6,
        img: "./img/Mục trang điểm/Son-thoi-AprilSkin-Ultra-Real-Matte-Lipstick.jpg",
        text: "Son Thỏi Aprilskin Ultra Real Matte Lipstick 3.7gr",
        pr_sales: "190,000₫",
        price: "213,000₫",
    },
    {
        id: 7,
        img: "./img/Mục trang điểm/Xịt-khoang-Kyung-Lab-PDRN-Therapy-Mist-150ml.jpg",
        text: "Xịt Khoáng Kyung Lab PDRN Therapy Mist 150ml",
        pr_sales: "360,000₫",
        price: "381,000₫",
    },
    {
        id: 8,
        img: "./img/Mục trang điểm/Dior-Addict-Lip-Glow-Oil-6ml.jpg",
        text: "Son Dưỡng Dior Addict Lip Glow Oil 6ml ",
        pr_sales: "320,000₫",
        price: "341,000₫",
    },
    {
        id: 9,
        img: "./img/Mục trang điểm/Son-3CE-Deep-Under-Soft-Matte-Lipstick-3_5gr.jpg",
        text: "Son 3CE Stylenanda Deep Under Soft Matte Lipstick 3.5gr",
        pr_sales: "280,000₫",
        price: "300,000₫",
    },
    {
        id: 10,
        img: "./img/Mục trang điểm/Son-tint-BBIA-Glow-Lip-Tint-3_2gr.jpg",
        text: "Son Tint Bóng BBia Glow Lip Tint 3.2gr",
        pr_sales: "150,000₫",
        price: "171,000₫",
    },
    {
        id: 11,
        img: "./img/Mục trang điểm/Mac-Locked-Kiss-Ink-4ml-3(1).jpg",
        text: "Son Kem MAC Locked Kiss Ink 4ml",
        pr_sales: "530,000₫",
        price: "649,000₫",
    },
    {
        id: 12,
        img: "./img/Mục trang điểm/BTS-Laneige-Lip-Sleeping-Mask.jpg",
        text: "Mặt Nạ Ngủ Môi Laneige BTS Lip Sleeping Mask Lip & Pop Edition (8gr x3) ",
        pr_sales: "160,000₫",
        price: "459,000₫",
    },
    {
        id: 13,
        img: "./img/Mục trang điểm/Shu-uemura-MBr784-minisize.jpg",
        text: "Son Shu Uemura RougeUnlimited Matte - Minisize",
        pr_sales: "290,000₫",
        price: "316,000₫",
    },
    {
        id: 14,
        img: "./img/Mục trang điểm/Ke-mat-Gogo-Tales-Fine-Make-Up-Eyeliner.jpg" ,
        text: "Kẻ Mắt Nước Gogo Tales Fine Make Up Eyeliner 0.6gr",
        pr_sales: "55,000₫",
        price: "76,000₫",
    },
    {
        id: 15,
        img: "./img/Mục trang điểm/Merzy-Academia-Cotton-Lipstick.jpg" ,
        text: "Son Thỏi Merzy Academia Cotton Lipstick 1.8gr",
        pr_sales: "190,000₫",
        price: "213,000₫",  
    },
    {
        id: 16,
        img: "./img/Mục trang điểm/Phan-phu-laneige-light-fit-pact.jpg" ,
        text: "Phấn Phủ Laneige Light Fit Pact 9.5gr",
        pr_sales: "550,000₫",
        price: "575,000₫",
    },
    {
        id: 17,
        img: "./img/Mục trang điểm/Kem-Lót-3CE-Stylenanda-Water-Make-Up-Base-45ml.jpg" ,
        text: "Kem Lót 3CE Stylenanda Water Make Up Base 45ml",
        pr_sales: "415,000₫",
        price: "442,000₫",
    },
    {
        id: 18,
        img: "./img/Mục trang điểm/Phấn-mắt-Lilybyred-Mood-Cheat-Kit.jpg" ,
        text: "Phấn Mắt Lilybyred Mood Cheat Kit 8gr",
        pr_sales: "240,000₫",
        price: "262,000₫",
    },
    {
        id: 19,
        img: "./img/Mục trang điểm/Laneige-NEO-Matte-Cushion.jpg",
        text: "Phấn Nước Laneige NEO Cushion Matte SPF42/PA++ (15gr x2)",
        pr_sales: "620,000₫",
        price: "641,000₫",
    },
    {
        id: 20,
        img:" ../img/Mục trang điểm/Black-Rouge-Air-Fit-Velvet-Tint-ver-9.jpg" ,
        text: "Son Kem Lì Black Rouge Air Fit Velvet Tint Ver.9 - 4.5gr",
        pr_sales: "160,000₫",
        price: "186,000₫",
    },
    {
        id: 21,
        img: "./img/Mục trang điểm/Phấn-Nước-April-Skin-Blossom-Edition-Hero-Cushion.jpg" ,
        text: "Phấn Nước April Skin Blossom Edition Hero Cushion (12gr + 3.5gr)",
        pr_sales: "450,000₫",
        price: "473,000₫",
    },
    {
        id: 22,
        img:"./img/Mục trang điểm/Nars-Lipstick-1_6gr.jpg",
        text: "Son Thỏi Nars Lipstick 1.6gr",
        pr_sales: "270,000₫",
        price: "291,000₫" ,
    },
    {
        id: 23,
        img:"./img/Mục trang điểm/Sáp-che-khuyết-điểm-tạo-khối-Odbo-Fix-Concealer-Shading-Stick-OD450.jpg",
        text: "Sáp Che Khuyết Điểm Và Tạo Khối Odbo Fix Concealer + Shading Stick - OD45",
        pr_sales: "85,000₫",
        price: "110,000₫",
    },
    {
        id: 24,
        img: "./img/Mục trang điểm/Set-Mặt-Nạ-ngủ-môi-Laneige-Lip-Sleeping-Mask-mini-kit-8gr.jpg" ,
        text: "Mặt Nạ Ngủ Môi Laneige Lip Sleeping Mask EX Mini Kit - 8g x 4",
        pr_sales: "310,000₫",
        price: "333,000₫",
    },
    // trang 2
    {
        id: 25,
        img: "./img/Mục trang điểm/trang 2/Che-khuyết-điểm-hiệu-chỉnh-tone-da-Revolution-Colour-Corrector-Palette.jpg",
        text: "Che Khuyết Điểm Revolution Colour Corrector Palette",
        pr_sales: "140,000₫",
        price: "159,000₫",
    },  
    
    {
        id: 26,
        img:" ../img/Mục trang điểm/trang 2/Chuốt-mi-và-kẻ-mắt-nước-NongChat-Browit-2-In-1-Universal-Mascara-and-Eyeliner.jpg",
        text: "Chuốt Mi Và Kẻ Mắt Nước NongChat Browit 2-In-1 Universal Mascara and Eyeline",
        pr_sales: "140,000₫",
        price: "170,000₫",
    },
    {
        id: 27,
        img: "./img/Mục trang điểm/SON-KEM-FOIF-Daily-Velvet-Tint.jpg",
        text: "Son Kem FOIF Daily Velvet Tint 3g",
        pr_sales: "140,000₫",
        price: "158,000₫",
    },
    {
        id: 28,
        img: "./img/Mục trang điểm/Phấn-Má-Hồng-Etude-House-Lovely-Cookie-Blusher-7gr.jpg",
        text: "Phấn Má Hồng Etud House Lovely Cookie Blusher 7gr",
        pr_sales: "110,000₫",
        price: "131,000₫", 
    },
    {
        id: 29,
        img: "./img/Mục trang điểm/phan-mat-habaria-Professional-10.jpg" ,
        text: "Phấn Mắt Habaria Professional 10 Colors Professional Eyeshadow Palette 10gr",
        pr_sales: "95,000₫",
        price: "118,000₫",
    },
    {
        id: 30,
        img: "./img/Mục trang điểm/Son-thoi-AprilSkin-Ultra-Real-Matte-Lipstick.jpg",
        text: "Son Thỏi Aprilski Ultra Real Matte Lipstick 3.7gr",
        pr_sales: "190,000₫",
        price: "213,000₫", 
    },
    {
        id: 31,
        img: "./img/Mục trang điểm/Xịt-khoang-Kyung-Lab-PDRN-Therapy-Mist-150ml.jpg",
        text: "Xịt Khoáng Kyung Lab PDRN Therapy Mist 150ml",
        pr_sales: "360,000₫",
        price: "381,000₫",
    },
    {
        id: 32,
        img: "./img/Mục trang điểm/Dior-Addict-Lip-Glow-Oil-6ml.jpg",
        text: "Son Dưỡng Dior Addict Lip Glow Oil 6m",
        pr_sales: "320,000₫",
        price: "341,000₫",
    },
    {
        id: 33,
        img: "./img/Mục trang điểm/Son-3CE-Deep-Under-Soft-Matte-Lipstick-3_5gr.jpg",
        text: "Son 3CE Stylenanda Deep Under Soft Matte Lipstick 3.5gr",
        pr_sales: "280,000₫",
        price: "300,000₫",
    },
    {
        id: 34,
        img: "./img/Mục trang điểm/Son-tint-BBIA-Glow-Lip-Tint-3_2gr.jpg",
        text: "Son Tint Bóng BBia Glow Lip Tint 3.2gr",
        pr_sales: "150,000₫",
        price: "171,000₫",
    },
    {
        id: 35,
        img: "./img/Mục trang điểm/Mac-Locked-Kiss-Ink-4ml-3(1).jpg",
        text: "Son Kem MAC Locked Kiss Ink 4ml",
        pr_sales: "530,000",
        price: "649,000₫",
    },
    {
        id: 36,
        img: "./img/Mục trang điểm/BTS-Laneige-Lip-Sleeping-Mask.jpg" ,
        text: "Mặt Nạ Ngủ Môi Laneige BTS Lip Sleeping Mask Lip & Pop Edition (8gr x3)",
        pr_sales: "160,000",
        price: "459,000₫",
    },
    {
        id: 37,
        img: "./img/Mục trang điểm/Shu-uemura-MBr784-minisize.jpg" ,
        text: "Son Shu Uemura Rouge Unlimited Matte - Minisize",
        pr_sales: "290,000₫",
        price: "316,000₫",
    },
    {
        id: 38,
        img: "./img/Mục trang điểm/Ke-mat-Gogo-Tales-Fine-Make-Up-Eyeliner.jpg" ,
        text: "Kẻ Mắt Nước Gogo Tales Fine Make Up Eyeliner 0.6gr",
        pr_sales: "55,000₫",
        price: "76,000₫",
    },
    {
        id: 39,
        img: "./img/Mục trang điểm/Merzy-Academia-Cotton-Lipstick.jpg" ,
        text: "Son Thỏi Merzy Academia Cotton Lipstick 1.8gr",
        pr_sales: "190,000₫",
        price: "213,000₫",
    },
    {
        id: 40,
        img: "./img/Mục trang điểm/Phan-phu-laneige-light-fit-pact.jpg" ,
        text: "Phấn Phủ Laneige Light Fit Pact 9.5gr",
        pr_sales: "550,000₫",
        price: "575,000₫",
    },
    {
        id: 41,
        img: "./img/Mục trang điểm/Kem-Lót-3CE-Stylenanda-Water-Make-Up-Base-45ml.jpg" ,
        text: "Kem Lót 3CE Stylenanda Water Make Up Base 45ml",
        pr_sales: "415,000₫",
        price: "442,000₫",
    },
    {
        id: 42,
        img: "./img/Mục trang điểm/Phấn-mắt-Lilybyred-Mood-Cheat-Kit.jpg" ,
        text: "Phấn Mắt Lilybyred Mood Cheat Kit 8gr",
        pr_sales: "240,000₫",
        price: "262,000₫",
    },
    {
        id: 43,
        img: "./img/Mục trang điểm/Laneige-NEO-Matte-Cushion.jpg",
        text: "Phấn Nước Laneige NEO Cushion Matte SPF42/PA++ (15gr x2)",
        pr_sales: "620,000₫",
        price: "641,000₫",
    },
    {
        id: 44,
        img: "./img/Mục trang điểm/Black-Rouge-Air-Fit-Velvet-Tint-ver-9.jpg" ,
        text: "Son Kem Lì Black Rouge Air Fit Velvet Tint Ver.9 - 4.5gr",
        pr_sales: "160,000₫",
        price: "186,000₫",
    },
    {
        id: 45,
        img: "./img/Mục trang điểm/trang 2/Bảng-màu-mắt-Fall-In-Love-Soft-Mate-Eyeshadow-Palette.jpg",
        text: "Phấn Nước April Skin Blossom Edition Hero Cushion (12gr + 3.5gr)",
        pr_sales: "450,000",
        price: "473,000₫",
    },
    {
        id: 46,
        img: "./img/Mục trang điểm/trang 2/Clio-Kill-Cover-Glow-Cushion.jpg",
        text: "Son Thỏi Nars Lipstick 1.6gr",
        pr_sales: "270,000₫",
        price: "291,000₫",
    },
    {
        id: 47,
        img:"./img/Mục trang điểm/trang 2/-merzy-v6-xanh-la-that-no.jpg" ,
        text: "Sáp Che Khuyết Điểm Và Tạo Khối Odbo Fix Concealer + Shading Stick - OD450",
        pr_sales: "85,000₫", 
        price: "110,000₫", 
    },
    {
        id: 48,
        img: "./img/Mục trang điểm/trang 2/Mặt-Nạ-Ngủ-Dưỡng-Môi-Laneige-Lip-Sleeping-Mask-EX-20gr.jpg" ,
        text: "Mặt Nạ Ngủ Môi Laneige Lip Sleeping Mask EX Mini Kit - 8g x 4",
        pr_sales: "310,000₫",
        price: "333,000",
    },

    // trag 3
    {
        id: 49,
        img: " ../img/Mục trang điểm/trang 2/Chuốt-mi-và-kẻ-mắt-nước-NongChat-Browit-2-In-1-Universal-Mascara-and-Eyeliner.jpg",
        text: "Chuốt Mi Và Kẻ Mắt Nước NongChat Browit 2-In-1 Universal Mascara and Eyeline",
        pr_sales: "140,000₫",
        price: "170,000₫",
    },
    {
        id: 50,
        img: "./img/Mục trang điểm/SON-KEM-FOIF-Daily-Velvet-Tint.jpg",
        text: "Son Kem FOIF Daily Velvet Tint 3g",
        pr_sales: "140,000₫",
        price: "158,000₫",
    },
    {
        id: 51,
        img: "./img/Mục trang điểm/Phấn-Má-Hồng-Etude-House-Lovely-Cookie-Blusher-7gr.jpg",
        text: "Phấn Má Hồng Etud House Lovely Cookie Blusher 7gr",
        pr_sales: "110,000₫",
        price: "131,000₫", 
    },
    {
        id: 52,
        img: "./img/Mục trang điểm/phan-mat-habaria-Professional-10.jpg" ,
        text: "Phấn Mắt Habaria Professional 10 Colors Professional Eyeshadow Palette 10gr",
        pr_sales: "95,000₫",
        price: "118,000₫",
    },
    {
        id: 53,
        img: "./img/Mục trang điểm/Son-thoi-AprilSkin-Ultra-Real-Matte-Lipstick.jpg",
        text: "Son Thỏi Aprilski Ultra Real Matte Lipstick 3.7gr",
        pr_sales: "190,000₫",
        price: "213,000₫", 
    },
    {
        id: 54,
        img: "./img/Mục trang điểm/Xịt-khoang-Kyung-Lab-PDRN-Therapy-Mist-150ml.jpg",
        text: "Xịt Khoáng Kyung Lab PDRN Therapy Mist 150ml",
        pr_sales: "360,000₫",
        price: "381,000₫",
    },
    {
        id: 55,
        img: "./img/Mục trang điểm/Dior-Addict-Lip-Glow-Oil-6ml.jpg",
        text: "Son Dưỡng Dior Addict Lip Glow Oil 6m",
        pr_sales: "320,000₫",
        price: "341,000₫",
    },
    {
        id: 56,
        img: "./img/Mục trang điểm/Son-3CE-Deep-Under-Soft-Matte-Lipstick-3_5gr.jpg",
        text: "Son 3CE Stylenanda Deep Under Soft Matte Lipstick 3.5gr",
        pr_sales: "280,000₫",
        price: "300,000₫",
    },
    {
        id: 57,
        img: "./img/Mục trang điểm/Son-tint-BBIA-Glow-Lip-Tint-3_2gr.jpg",
        text: "Son Tint Bóng BBia Glow Lip Tint 3.2gr",
        pr_sales: "150,000₫",
        price: "171,000₫",
    },
    {
        id: 58,
        img: "./img/Mục trang điểm/Mac-Locked-Kiss-Ink-4ml-3(1).jpg",
        text: "Son Kem MAC Locked Kiss Ink 4ml",
        pr_sales: "530,000",
        price: "649,000₫",
    },
    {
        id: 59,
        img: "./img/Mục trang điểm/BTS-Laneige-Lip-Sleeping-Mask.jpg",
        text: "Mặt Nạ Ngủ Môi Laneige BTS Lip Sleeping Mask Lip & Pop Edition (8gr x3)",
        pr_sales: "160,000",
        price: "459,000₫",
    },
    {
        id: 60,
        img: "./img/Mục trang điểm/Shu-uemura-MBr784-minisize.jpg",
        text: "Son Shu Uemura Rouge Unlimited Matte - Minisize",
        pr_sales: "290,000₫",
        price: "316,000₫",
    },
    {
        id: 61,
        img: "./img/Mục trang điểm/Ke-mat-Gogo-Tales-Fine-Make-Up-Eyeliner.jpg",
        text: "Kẻ Mắt Nước Gogo Tales Fine Make Up Eyeliner 0.6gr",
        pr_sales: "55,000₫",
        price: "76,000₫",
    },
    {
        id: 62,
        img: "./img/Mục trang điểm/Merzy-Academia-Cotton-Lipstick.jpg",
        text: "Son Thỏi Merzy Academia Cotton Lipstick 1.8gr",
        pr_sales: "190,000₫",
        price: "213,000₫",
    },
    {
        id: 63,
        img: "./img/Mục trang điểm/Phan-phu-laneige-light-fit-pact.jpg",
        text: "Phấn Phủ Laneige Light Fit Pact 9.5gr",
        pr_sales: "550,000₫",
        price: "575,000₫",
    },
    {
        id: 64,
        img: "./img/Mục trang điểm/Kem-Lót-3CE-Stylenanda-Water-Make-Up-Base-45ml.jpg",
        text: "Kem Lót 3CE Stylenanda Water Make Up Base 45ml",
        pr_sales: "415,000₫",
        price: "442,000₫",
    },
    {
        id: 65,
        img: "./img/Mục trang điểm/Phấn-mắt-Lilybyred-Mood-Cheat-Kit.jpg" ,
        text: "Phấn Mắt Lilybyred Mood Cheat Kit 8gr",
        pr_sales: "240,000₫",
        price: "262,000₫",
    },
    {
        id: 66,
        img: "./img/Mục trang điểm/Laneige-NEO-Matte-Cushion.jpg",
        text: "Phấn Nước Laneige NEO Cushion Matte SPF42/PA++ (15gr x2)",
        pr_sales: "620,000₫",
        price: "641,000₫",
    },
    {
        id: 67,
        img: "./img/Mục trang điểm/Laneige-NEO-Matte-Cushion.jpg",
        text: "Phấn Nước Laneige NEO Cushion Matte SPF42/PA++ (15gr x2)",
        pr_sales: "620,000₫",
        price: "641,000₫",
    },
    {
        id: 68,
        img:" ../img/Mục trang điểm/Black-Rouge-Air-Fit-Velvet-Tint-ver-9.jpg",
        text: "Son Kem Lì Black Rouge Air Fit Velvet Tint Ver.9 - 4.5gr",
        pr_sales: "160,000₫",
        price: "186,000₫",
    },
    {
        id: 69,
        img: "./img/Mục trang điểm/trang 2/Peripera-Ink-Mood-Matte-Stick.jpg",
        text: "Phấn Nước April Skin Blossom Edition Hero Cushion (12gr + 3.5gr)",
        pr_sales: "450,000₫",
        price: "473,000₫",
    },
    {
        id: 70,
        img: "./img/Mục trang điểm//trang 2/Bang-che-khuyet-diem-mangogo.jpg",
        text: "Son Thỏi Nars Lipstick 1.6gr",
        pr_sales: "270,000₫",
        price: "291,000₫",
    },
    {
        id: 71,
        img: "./img/Mục trang điểm/trang 2/Phấn-mắt-trang-điểm-Sivanna-Colors-Fox-Frog-Eyeshadow-Palette-11gr-HF158.jpg",
        text: "Sáp Che Khuyết Điểm Và Tạo Khối Odbo Fix Concealer + Shading Stick - OD45",
        pr_sales: "85,000₫",
        price: "110,000₫",
    },
    {
        id: 72,
        img: "./img/Mục trang điểm/trang 2/-merzy-v6-xanh-la-that-no.jpg",
        text: "Mặt Nạ Ngủ Môi Laneige Lip Sleeping Mask EX Mini Kit - 8g x 4",
        pr_sales: "310,000₫",
        price: "333,000",
    },
];