export default [
    {
        id: 1,
        img: '../img/San_pham_noi_bat/Avatar-SP-Web(1)(1)-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered-Recovered(3).jpg',
        text: 'Nước Cân Bằng Klairs Supple Preparation',
        pr_sales: '260,000₫',
        price: '306,000₫',
    },
    {
        id: 2,
        img: '../img/San_pham_noi_bat/Kem-chống-nắng-Heliocare-360-Protector-Solar-Mineral-Tolerance-Fluid-Sunscreen-SPF50-50ml.jpg',
        text: "Kem Chống Nắng Heliocare 360 Protector...",
        pr_sales: '470,000₫',
        price: '540,000₫',
    },
    {
        id: 3,
        img: '../img/San_pham_noi_bat/Kem-chống-nắng-Heliocare-360-Protector-Solar-Water-Gel-Sunscreen-SPF50.jpg',
        text: "Kem Chống Nắng Heliocare 360 Protector...",
        pr_sales: '490,000₫',
        price: '543,000₫',
    },
    {
        id: 4,
        img: '../img/San_pham_noi_bat/Kem-Dưỡng-Da-Obagi-Medical-Retinol-1_0-Cream.jpg',
        text: "Kem Dưỡng Da Obagi Medical Retinol 1.0 Cream ",
        pr_sales: '1,190,000₫',
        price: '1,412,000₫',
    },
    {
        id: 5,
        img: '../img/San_pham_noi_bat/Avatar-SP-Web(1)(1)-Recovered(29).jpg',
        text: "Dung Dịch Loại Bỏ Mụn Obagi Medical Salicylic...",
        pr_sales: '650,000₫',
        price: '802,000₫',
    },
    {
        id: 6,
        img: '../img/San_pham_noi_bat/Obagi-Medical-C-Clarifying-Serum.jpg',
        text: "Tinh Chất Obagi Medical C - Rx C - Clarifying",
        pr_sales: '2,200,000₫',
        price: '2,220,000₫',
    },
    {
        id: 7,
        img: '../img/San_pham_noi_bat/Kem-dưỡng-trẻ-hóa-và-săn-chắc-vùng-da-cổ-Medi-Peel-Naite-Thread-Neck-Cream-100ml.jpg',
        text: "Kem Dưỡng Trẻ Hóa Và Săn Chắc Vùng Da Cổ...",
        pr_sales: '280,000₫',
        price: '304,000₫',
    },
    {
        id: 8,
        img: '../img/San_pham_noi_bat/Tinh-chất-dưỡng-trắng-da-Garnier-Skin-Naturals-Vitamin-C-Booster-Serum-30ml.jpg',
        text: "Tinh Chất Dưỡng Trắng Da Garnier Skin Naturals...",
        pr_sales: '220,000₫',
        price: '244,000₫',
    },
    {
        id: 9,
        img: '../img/San_pham_noi_bat/Sữa-tắm-hương-nước-hoa-Tesori-DOriente-Bath-Cream-250ml.jpg',
        text: "Sữa Tắm Hương Nước Hoa Tesori D'Oriente Bat...",
        pr_sales: '130,000₫',
        price: '150,000₫',
    },
];


export const data2 = [
    {
        id: 1,
        img: '../img/San_pham_moi_ve/Serum-K-Lady-Care-Retinol-Bakuchiol-50ml.jpg',
        text: "Tinh Chất K Lady Care Bakuchiol Retinol Serum Chống Lão Hóa 50ml",
        pr_sales: '310,000₫',
        price: '331,000₫',
    },
    {
        id: 2,
        img: '../img/San_pham_moi_ve/Kem-duong-Dr_Sunmi-HA-Plus-Cream(1).jpg',
        text: "Kem Dưỡng Dr.Sunmi Care HA Plus 100DT Cream 50ml",
        pr_sales: '350,000₫',
        price: '368,000₫',
    },
    {
        id: 3,
        img: '../img/San_pham_moi_ve/nuoc-tay-trang-Loreal-paris-Revitalift-Hyauronic-Acid-Micellar-Water-95ml.jpg',
        text: "Nước Tẩy Trang L'Oreal Revitalift Hyauronic Acid Micellar Water 95ml",
        pr_sales: '80,000₫',
        price: '102,000₫',
    },
    {
        id: 4,
        img: '../img/San_pham_moi_ve/sua-rua-mat-Byvibes-Wonder-Bath-PHA-5_5-PH-Balancing-PHA-Cleansing-Foam-150ml.jpg',
        text: "Sữa text: 'Rửa Mặt Byvibes Wonder Bath PHA 5.5 Cleansing Foam 150ml",
        pr_sales: '180,000₫',
        price: '199,000₫',
    },
    {
        id: 5,
        img: '../img/San_pham_moi_ve/nuoc-tay-trang-PrettySkin-The-Pure-Jeju-Cica-Cleansing-Water-500ml.jpg',
        text: "Nước Tẩy Trang PrettySkin The Pure Jeju Cica Cleansing Water 500ml",
        pr_sales: '180,000₫',
        price: '205,000₫',
    },
    {
        id: 6,
        img: '../img/San_pham_moi_ve/serum-LOreal-Paris-Hyaluronic-Acid.jpg',
        text: "Tinh Chất L'Oreal Paris Hyaluronic Acid 1.5% - 30ml",
        pr_sales: '420,000₫',
        price: '443,000₫',
    },
    {
        id: 7,
        img: '../img/San_pham_moi_ve/tay-trang-LOreal-Paris-Micellar-Water-Revitalift.jpg',
        text: "Nước Tẩy Trang L'Oreal Làm Sạch & Dưỡng Ẩm Revitalift Micellar Water 400ml",
        pr_sales: '230,000₫',
        price: '250,000₫',
    },
    {
        id: 8,
        img: '../img/San_pham_moi_ve/Kem-u-toc-Cocoon-Pomelo-Hair-Mask-200ml.jpg',
        text: "Kem Ủ Tóc Bưởi Cocoon Pomelo Hair Mask 200ml",
        pr_sales: '215,000₫',
        price: '236,000₫',
    },
    {
        id: 9,
        img: '../img/San_pham_moi_ve/Mat-na-Martiderm-Moisturising-Mask-25ml.jpg',
        text: "Mặt Nạ Martiderm Moisturising Mask 25ml",
        pr_sales: '35,000₫',
        price: '62,000₫',
    },
    {
        id: 10,
        img: '../img/San_pham_moi_ve/SON-KEM-FOIF-Daily-Velvet-Tint.jpg',
        text: "Son Kem FOIF Daily Velvet Tint 3gr",
        pr_sales: '140,000₫',
        price: '158,000₫',
    },
    {
        id: 11,
        img: '../img/San_pham_moi_ve/Serum-Dr_Sunmi-care-HA-plus.jpg',
        text: "Tinh Chất Dr.Sunmi Care HA Plus 100ml",
        pr_sales: '380,000₫',
        price: '404,000₫',
    },
    {
        id: 12,
        img: '../img/San_pham_moi_ve/Kem-Chong-Nang-La-Roche-Posay-UVMune-400-Fluid-Oil-Control.jpg',
        text: "Kem Chống Nắng La Roche-Posay Anthelios UVMune 400 Fluide Oil Control 50ml",
        pr_sales: '420,000₫',
        price: '441,000₫',
    }, 
]; 

export const data3 = [
    {
        id: 1,
        img: "../img/Sản phẩm trang điểm/a3-03112018023519.jpg",
        text: "Phấn Nước Missha Magic Cushion Cover Lasting",
        pr_sales: "160,000₫",
        price: "197,000₫",
    },
    {
        id: 2,
        img: "../img/Sản phẩm trang điểm/moistyup.jpg",
        text: "Phấn Nước Missha Magic Cushion Moist Up", 
        pr_sales: "160,000₫",
        price: "178,000₫",
    },
    {
        id: 3,
        img: "../img/Sản phẩm trang điểm/01(9).jpg",
        text: "Kem Lót Kiềm Dầu Maybelline Baby Skin Primer",
        pr_sales: "155,000₫",
        price: "183,000₫",
    },
    {
        id: 4,
        img: "../img/Sản phẩm trang điểm/kem-che-khuyet-diem-The-Saem-Cover-Perfection-Tip-Concealer1.jpg",
        text: "Kem Che Khuyết Điểm The Saem Cover Perfection SPF28/PA++ 6.5gr",
        pr_sales: "90,000₫",
        price: "99,000₫",
    },
    {
        id: 5,
        img: "../img/Sản phẩm trang điểm/01(91).jpg",
        text: "Phấn Nước Missha Velvet Cushion 15gr",
        pr_sales: "195,000₫",
        price: "210,000₫",
    },
    {
        id: 6,
        img: "../img/Sản phẩm trang điểm/a6-10102018102301.jpg",
        text: "Kem Che Khuyết Điểm L.A Girl Pro.Conceal HD",
        pr_sales: "85,000₫",
        price: "106,000₫",
    },
    {
        id: 7,
        img: "../img/Sản phẩm trang điểm/che-khuyet-diem-Maybelline.jpg",
        text: "Xịt khoáng Pháp Evoluderm 400ml",
        pr_sales: "140,000₫",
        price: "194,000₫",
    },
    {
        id: 8,
        img: "../img/Sản phẩm trang điểm/Che-khuyết-điểm-hiệu-chỉnh-tone-da-Revolution-Colour-Corrector-Palette.jpg",
        text: "Kem che khuyết điểm Maybelline Fit Me Concealer", 
        pr_sales: "150,000₫",
        price: "205,000₫",
    },
    {
        id: 9,
        img: "../img/Sản phẩm trang điểm/xit-khoang-phap-EvoLuderm-eau-pure-beauty-garden-1(1).jpg",
        text: "Phấn Nén Karadium Collagen Smart Sun Pact",
        pr_sales: "210,000₫",
        price: "246,000₫",
    },
    {
        id: 10,
        img: "../img/Sản phẩm trang điểm/01-21082018041015.jpg",
        text: "Che Khuyết Điểm Revolution Colour Corrector Palette",
        pr_sales: "140,000₫",
        price: "159,000₫",
    },
    {
        id: 11,
        img: "../img/Sản phẩm trang điểm/Avatar-SP-Web(1)(1)-Recovered(13).jpg",
        text: "Catrice All Round Concealer Palette",
        pr_sales: "110,000₫",
        price: "173,000₫",
    },
    {
        id: 12,
        img: "../img/Sản phẩm trang điểm/Avatar-SP-Web(1)(1)-Recovered(9).jpg",
        text: "Bảng Tạo Khối Odbo Highlight & Contour", 
        pr_sales: "120,000₫",
        price: "174,000₫",
    },
];